apiVersion: v1
kind: Namespace
metadata:
  name: ssh-test
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ssh
  namespace: ssh-test
spec:
  serviceName: "ssh"
  replicas: 25
  selector:
    matchLabels:
      app: ssh
  template:
    metadata:
      labels:
        app: ssh
    spec:
      containers:
      - name: ssh
        image: ghcr.io/pbar1/ssh-benchmark-server
        ports:
        - containerPort: 2222
          name: ssh
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ssh
  namespace: ssh-test
spec:
  selector:
    app: ssh
  clusterIP: None # headless service
  ports:
  - name: port-0
    port: 2222
    targetPort: ssh
  - name: port-1
    port: 2223
    targetPort: ssh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - image: ghcr.io/pbar1/ssh-benchmark-client
        name: client
        command:
        - sleep
        - "1000000"

