version: "3"

tasks:
  default: task --list

  img:server:
    cmd: docker build --file server/Dockerfile --tag ghcr.io/pbar1/ssh-benchmark-server:latest .

  img:client:
    cmd: docker build --file client/Dockerfile --tag ghcr.io/pbar1/ssh-benchmark-client:latest .
