apiVersion: batch/v1
kind: Job
metadata:
  name: client-10000
  namespace: ssh-benchmark
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - command:
        - client
        - --concurrency=10000
        env:
        - name: TOKIO_CONSOLE_BIND
          value: 0.0.0.0:6669
        - name: RUST_LOG
          value: info
        image: ghcr.io/pbar1/ssh-benchmark-client:latest
        name: client
        ports:
        - containerPort: 6669
          name: tokio-console
        resources:
          limits:
            memory: 3Gi
          requests:
            memory: 3Gi
      restartPolicy: Never
