apiVersion: batch/v1
kind: Job
metadata:
  name: client-1000
  namespace: ssh-benchmark
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - command:
        - client
        - --concurrency=1000
        image: ghcr.io/pbar1/ssh-benchmark-client:latest
        name: client
        resources:
          limits:
            memory: 3Gi
          requests:
            memory: 3Gi
      restartPolicy: Never
