apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: ssh-benchmark
spec:
  clusterIP: None
  ports:
  - name: ssh-0
    port: 20000
    targetPort: ssh-0
  - name: ssh-1
    port: 20001
    targetPort: ssh-1
  - name: ssh-2
    port: 20002
    targetPort: ssh-2
  - name: ssh-3
    port: 20003
    targetPort: ssh-3
  - name: ssh-4
    port: 20004
    targetPort: ssh-4
  - name: ssh-5
    port: 20005
    targetPort: ssh-5
  - name: ssh-6
    port: 20006
    targetPort: ssh-6
  - name: ssh-7
    port: 20007
    targetPort: ssh-7
  - name: ssh-8
    port: 20008
    targetPort: ssh-8
  - name: ssh-9
    port: 20009
    targetPort: ssh-9
  selector:
    app: server
