apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: ssh-benchmark
spec:
  clusterIP: None
  ports:
  - name: ssh-0
    port: 20000
    targetPort: ssh-0
  - name: ssh-1
    port: 20001
    targetPort: ssh-1
  - name: ssh-2
    port: 20002
    targetPort: ssh-2
  - name: ssh-3
    port: 20003
    targetPort: ssh-3
  - name: ssh-4
    port: 20004
    targetPort: ssh-4
  - name: ssh-5
    port: 20005
    targetPort: ssh-5
  - name: ssh-6
    port: 20006
    targetPort: ssh-6
  - name: ssh-7
    port: 20007
    targetPort: ssh-7
  - name: ssh-8
    port: 20008
    targetPort: ssh-8
  - name: ssh-9
    port: 20009
    targetPort: ssh-9
  - name: ssh-10
    port: 20010
    targetPort: ssh-10
  - name: ssh-11
    port: 20011
    targetPort: ssh-11
  - name: ssh-12
    port: 20012
    targetPort: ssh-12
  - name: ssh-13
    port: 20013
    targetPort: ssh-13
  - name: ssh-14
    port: 20014
    targetPort: ssh-14
  - name: ssh-15
    port: 20015
    targetPort: ssh-15
  - name: ssh-16
    port: 20016
    targetPort: ssh-16
  - name: ssh-17
    port: 20017
    targetPort: ssh-17
  - name: ssh-18
    port: 20018
    targetPort: ssh-18
  - name: ssh-19
    port: 20019
    targetPort: ssh-19
  - name: ssh-20
    port: 20020
    targetPort: ssh-20
  - name: ssh-21
    port: 20021
    targetPort: ssh-21
  - name: ssh-22
    port: 20022
    targetPort: ssh-22
  - name: ssh-23
    port: 20023
    targetPort: ssh-23
  - name: ssh-24
    port: 20024
    targetPort: ssh-24
  - name: ssh-25
    port: 20025
    targetPort: ssh-25
  - name: ssh-26
    port: 20026
    targetPort: ssh-26
  - name: ssh-27
    port: 20027
    targetPort: ssh-27
  - name: ssh-28
    port: 20028
    targetPort: ssh-28
  - name: ssh-29
    port: 20029
    targetPort: ssh-29
  - name: ssh-30
    port: 20030
    targetPort: ssh-30
  - name: ssh-31
    port: 20031
    targetPort: ssh-31
  - name: ssh-32
    port: 20032
    targetPort: ssh-32
  - name: ssh-33
    port: 20033
    targetPort: ssh-33
  - name: ssh-34
    port: 20034
    targetPort: ssh-34
  - name: ssh-35
    port: 20035
    targetPort: ssh-35
  - name: ssh-36
    port: 20036
    targetPort: ssh-36
  - name: ssh-37
    port: 20037
    targetPort: ssh-37
  - name: ssh-38
    port: 20038
    targetPort: ssh-38
  - name: ssh-39
    port: 20039
    targetPort: ssh-39
  - name: ssh-40
    port: 20040
    targetPort: ssh-40
  - name: ssh-41
    port: 20041
    targetPort: ssh-41
  - name: ssh-42
    port: 20042
    targetPort: ssh-42
  - name: ssh-43
    port: 20043
    targetPort: ssh-43
  - name: ssh-44
    port: 20044
    targetPort: ssh-44
  - name: ssh-45
    port: 20045
    targetPort: ssh-45
  - name: ssh-46
    port: 20046
    targetPort: ssh-46
  - name: ssh-47
    port: 20047
    targetPort: ssh-47
  - name: ssh-48
    port: 20048
    targetPort: ssh-48
  - name: ssh-49
    port: 20049
    targetPort: ssh-49
  - name: ssh-50
    port: 20050
    targetPort: ssh-50
  - name: ssh-51
    port: 20051
    targetPort: ssh-51
  - name: ssh-52
    port: 20052
    targetPort: ssh-52
  - name: ssh-53
    port: 20053
    targetPort: ssh-53
  - name: ssh-54
    port: 20054
    targetPort: ssh-54
  - name: ssh-55
    port: 20055
    targetPort: ssh-55
  - name: ssh-56
    port: 20056
    targetPort: ssh-56
  - name: ssh-57
    port: 20057
    targetPort: ssh-57
  - name: ssh-58
    port: 20058
    targetPort: ssh-58
  - name: ssh-59
    port: 20059
    targetPort: ssh-59
  - name: ssh-60
    port: 20060
    targetPort: ssh-60
  - name: ssh-61
    port: 20061
    targetPort: ssh-61
  - name: ssh-62
    port: 20062
    targetPort: ssh-62
  - name: ssh-63
    port: 20063
    targetPort: ssh-63
  - name: ssh-64
    port: 20064
    targetPort: ssh-64
  - name: ssh-65
    port: 20065
    targetPort: ssh-65
  - name: ssh-66
    port: 20066
    targetPort: ssh-66
  - name: ssh-67
    port: 20067
    targetPort: ssh-67
  - name: ssh-68
    port: 20068
    targetPort: ssh-68
  - name: ssh-69
    port: 20069
    targetPort: ssh-69
  - name: ssh-70
    port: 20070
    targetPort: ssh-70
  - name: ssh-71
    port: 20071
    targetPort: ssh-71
  - name: ssh-72
    port: 20072
    targetPort: ssh-72
  - name: ssh-73
    port: 20073
    targetPort: ssh-73
  - name: ssh-74
    port: 20074
    targetPort: ssh-74
  - name: ssh-75
    port: 20075
    targetPort: ssh-75
  - name: ssh-76
    port: 20076
    targetPort: ssh-76
  - name: ssh-77
    port: 20077
    targetPort: ssh-77
  - name: ssh-78
    port: 20078
    targetPort: ssh-78
  - name: ssh-79
    port: 20079
    targetPort: ssh-79
  - name: ssh-80
    port: 20080
    targetPort: ssh-80
  - name: ssh-81
    port: 20081
    targetPort: ssh-81
  - name: ssh-82
    port: 20082
    targetPort: ssh-82
  - name: ssh-83
    port: 20083
    targetPort: ssh-83
  - name: ssh-84
    port: 20084
    targetPort: ssh-84
  - name: ssh-85
    port: 20085
    targetPort: ssh-85
  - name: ssh-86
    port: 20086
    targetPort: ssh-86
  - name: ssh-87
    port: 20087
    targetPort: ssh-87
  - name: ssh-88
    port: 20088
    targetPort: ssh-88
  - name: ssh-89
    port: 20089
    targetPort: ssh-89
  - name: ssh-90
    port: 20090
    targetPort: ssh-90
  - name: ssh-91
    port: 20091
    targetPort: ssh-91
  - name: ssh-92
    port: 20092
    targetPort: ssh-92
  - name: ssh-93
    port: 20093
    targetPort: ssh-93
  - name: ssh-94
    port: 20094
    targetPort: ssh-94
  - name: ssh-95
    port: 20095
    targetPort: ssh-95
  - name: ssh-96
    port: 20096
    targetPort: ssh-96
  - name: ssh-97
    port: 20097
    targetPort: ssh-97
  - name: ssh-98
    port: 20098
    targetPort: ssh-98
  - name: ssh-99
    port: 20099
    targetPort: ssh-99
  selector:
    app: server
