name: ci

on:
  push:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push (server)
      uses: docker/build-push-action@v5
      with:
        file: server/Dockerfile
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/pbar1/ssh-benchmark-server:latest
